<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/02/23 11:14:52
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 10,
));
