<?php
// auto-generated by sfCacheConfigHandler
// date: 2016/02/23 11:14:53
$this->addCache($moduleName, 'new', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'index', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

